import { spawn } from 'child_process';
import fs from 'fs';
import path from 'path';

export class PostProcessor {
  /**
   * Merges an array of local video file paths sequentially into a single final video.
   * Uses ffmpeg concat demuxer which is fast and preserves original encoding if properties match.
   * If properties differ, it falls back to a complex filtergraph, but for MVP we assume 
   * clips generated by the same Gemini model share the same resolution and codec.
   * 
   * @param {string[]} inputPaths - Array of absolute paths to the downloaded video clips
   * @param {string} outputPath - Absolute path for the final merged video
   * @returns {Promise<string>} Path to the successfully merged video
   */
  async mergeVideos(inputPaths, outputPath) {
    if (!inputPaths || inputPaths.length === 0) {
      throw new Error("No input paths provided for merging.");
    }
    
    if (inputPaths.length === 1) {
      console.log(`[PostProcessor] Only 1 clip provided, simply copying to destination.`);
      fs.copyFileSync(inputPaths[0], outputPath);
      return outputPath;
    }

    console.log(`[PostProcessor] Preparing to merge ${inputPaths.length} clips into ${outputPath}`);

    // Create a temporary text file listing the input files for ffmpeg concat demuxer
    const tempDir = path.dirname(outputPath);
    const listFilePath = path.join(tempDir, `concat_list_${Date.now()}.txt`);
    
    // Format required by ffmpeg: file '/absolute/path/to/file.mp4'
    const listContent = inputPaths.map(p => `file '${p.replace(/'/g, "'\\''")}'`).join('\n');
    fs.writeFileSync(listFilePath, listContent);

    return new Promise((resolve, reject) => {
      // For MVP: Simple concat. 
      // -safe 0 allows absolute paths in the text file
      // -c copy attempts to copy streams without re-encoding (extremely fast).
      // We will also use -y to overwrite the output file if it exists.
      
      const args = [
        '-y',
        '-f', 'concat',
        '-safe', '0',
        '-i', listFilePath,
        '-c', 'copy',
        outputPath
      ];

      console.log(`[PostProcessor] Running ffmpeg: ffmpeg ${args.join(' ')}`);

      const ffmpegProcess = spawn('ffmpeg', args);
      
      let stderrLog = '';
      ffmpegProcess.stderr.on('data', (data) => {
        stderrLog += data.toString();
      });

      ffmpegProcess.on('close', (code) => {
        // Clean up the temp list file
        if (fs.existsSync(listFilePath)) {
          fs.unlinkSync(listFilePath);
        }

        if (code === 0) {
          console.log(`[PostProcessor] Successfully merged videos to: ${outputPath}`);
          resolve(outputPath);
        } else {
          console.error(`[PostProcessor] FFmpeg failed with exit code ${code}. Stderr: ${stderrLog}`);
          
          // Fallback to re-encoding if concat demuxer fails due to mismatched streams
          console.log("[PostProcessor] Attempting fallback re-encoding merge...");
          this.fallbackMerge(inputPaths, outputPath)
            .then(resolve)
            .catch(reject);
        }
      });
      
      ffmpegProcess.on('error', (err) => {
        if (fs.existsSync(listFilePath)) fs.unlinkSync(listFilePath);
        reject(new Error(`Failed to start ffmpeg process: ${err.message}`));
      });
    });
  }

  /**
   * Fallback merge method using complex filtergraph. Slower but robust against mismatched resolutions/codecs.
   */
  async fallbackMerge(inputPaths, outputPath) {
    return new Promise((resolve, reject) => {
      let args = ['-y'];
      inputPaths.forEach(p => {
        args.push('-i', p);
      });

      // Build filter complex: [0:v][0:a][1:v][1:a]... concat=n=N:v=1:a=1 [v][a]
      let filterStr = '';
      for (let i = 0; i < inputPaths.length; i++) {
        filterStr += `[${i}:v:0][${i}:a:0]`;
      }
      filterStr += `concat=n=${inputPaths.length}:v=1:a=1[outv][outa]`;

      args.push('-filter_complex', filterStr);
      args.push('-map', '[outv]', '-map', '[outa]');
      args.push('-vsync', '2'); // Drop/duplicate frames to achieve target frame rate
      args.push(outputPath);

      console.log(`[PostProcessor] Running fallback ffmpeg: ffmpeg ${args.join(' ')}`);

      const ffmpegProcess = spawn('ffmpeg', args);
      
      let errLog = '';
      ffmpegProcess.stderr.on('data', (data) => errLog += data.toString());

      ffmpegProcess.on('close', (code) => {
        if (code === 0) {
          console.log(`[PostProcessor] Successfully merged videos (fallback) to: ${outputPath}`);
          resolve(outputPath);
        } else {
          reject(new Error(`Fallback FFmpeg merge failed with code ${code}: ${errLog}`));
        }
      });
    });
  }
}
